### ISSUE TITLE
README seems to be out of synch with implementation

### ISSUE THREAD

**Issue by peeterjoot** [digitaldomain/Multivectors.jl#3]
1) grade function not callable?

julia> A=e₂ * e₃
e₂₃

julia> grade(A,0)
ERROR: MethodError: no method matching grade(::Type{e₂₃}, ::Int64)
Closest candidates are:
  grade(::Type{B}) where B<:Blade at ~/.julia/packages/Multivectors/Qt23X/src/Blades.jl:796
  grade(::KVector{T, K}, ::Integer) where {T, K} at ~/.julia/packages/Multivectors/Qt23X/src/KVectors.jl:138
  grade(::Multivector{T, N}, ::Any) where {T, N} at ~/.julia/packages/Multivectors/Qt23X/src/Multivectors.jl:256
  ...
Stacktrace:
 [1] top-level scope
   @ REPL[25]:1

julia> grade(A,1)
ERROR: MethodError: no method matching grade(::Type{e₂₃}, ::Int64)
Closest candidates are:
  grade(::Type{B}) where B<:Blade at ~/.julia/packages/Multivectors/Qt23X/src/Blades.jl:796
  grade(::KVector{T, K}, ::Integer) where {T, K} at ~/.julia/packages/Multivectors/Qt23X/src/KVectors.jl:138
  grade(::Multivector{T, N}, ::Any) where {T, N} at ~/.julia/packages/Multivectors/Qt23X/src/Multivectors.jl:256
  ...
Stacktrace:
 [1] top-level scope
   @ REPL[26]:1

julia> grade(A,2)
ERROR: MethodError: no method matching grade(::Type{e₂₃}, ::Int64)
Closest candidates are:
  grade(::Type{B}) where B<:Blade at ~/.julia/packages/Multivectors/Qt23X/src/Blades.jl:796
  grade(::KVector{T, K}, ::Integer) where {T, K} at ~/.julia/packages/Multivectors/Qt23X/src/KVectors.jl:138
  grade(::Multivector{T, N}, ::Any) where {T, N} at ~/.julia/packages/Multivectors/Qt23X/src/Multivectors.jl:256
  ...
Stacktrace:
 [1] top-level scope
   @ REPL[27]:1

2) barycoords function from the README doesn't work:

julia> barycoords(A)
ERROR: UndefVarError: barycoords not defined
Stacktrace:
 [1] top-level scope
   @ REPL[28]:1

3) I can't figure out how to specify a dot product.  Early in the docs, it looks like this would be done with \cdot[tab].  That correctly introduces the cdot symbol, but it doesn't work:

julia> A⋅B
ERROR: UndefVarError: ⋅ not defined
Stacktrace:
 [1] top-level scope
   @ REPL[32]:1

The README also refers to left-contraction.  If that is available in the repl, it's not clear how:

julia> A \lcontraction[tab] B

expands to just:

julia> A \lcontraction B
ERROR: syntax: extra token "B" after end of expression
Stacktrace:
 [1] top-level scope
   @ none:1

4) docs mention a reverse() function.  I tried this two different ways, both failed:

julia> reverse(A)
ERROR: MethodError: no method matching reverse(::Type{e₂₃})
Closest candidates are:
  reverse(::Union{SubString{String}, String}) at /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/base/strings/substring.jl:166
  reverse(::T) where T<:Real at ~/.julia/packages/Multivectors/Qt23X/src/Multivectors.jl:338
  reverse(::Pair{A, B}) where {A, B} at /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/base/pair.jl:48
  ...
Stacktrace:
 [1] top-level scope
   @ REPL[35]:1

julia> A->reverse()
#4 (generic function with 1 method)

**Comment by peeterjoot** [comment]
It occurred to me that perhaps the Multivector package that is available through:

import Pkg; Pkg.add("Multivectors")

is too old, relative to this README.  Do I have to update to "latest", and if so, how would that be done?

**Comment by moble** [comment]
You seem to be right: the [current version in Project.toml](https://github.com/digitaldomain/Multivectors.jl/blob/8898b44d604ffddd41ea2035a597138ec2344c4d/Project.toml#L4) is "0.3.1", whereas `Pkg.status()` says it has "0.3.0".  To get the current git version, you can do `Pkg.add(url="https://github.com/digitaldomain/Multivectors.jl")`.  Still doesn't resolve your issues, though...

**Comment by peeterjoot** [comment]
Looks like the answer in:

https://github.com/digitaldomain/Multivectors.jl/issues/2

explains most of these troubles.  

1) The grade() troubles are resolved by that:


julia> e1 = 1e₁
1e₁

julia> e2 = 1e₂
1e₂

julia> e3 = 1e₃
1e₃

julia> e1 ∧ e2
1e₁₂

julia> e2 ∧ e3
1e₂₃

julia> e3 ∧ e1
-1e₁₃

julia> A = e2 ∧ e3
1e₂₃

julia> grade(A,0)
0

julia> grade(A,1)
0

julia> grade(A,2)
1-element KVector{Int64, 2, 1}:
 1e₂₃

2) Re: barycoords().  I failed to notice that this isn't a built in function, but was an example that requires:

barycoords(p) = ((c-b)∧(p-b)/A, (a-c)∧(p-c)/A, (b-a)∧(p-a)/A)  # a tuple of coords

3) I'm not sure how to symbolically enter the left and right contraction operators, but this now works as a function call, as does rcontraction:

julia> C=1e₂
1e₂

julia> lcontraction(C,A)
1e₃

julia> lcontraction(A,C)
0

julia> rcontraction(A,C)
1e₃

julia> rcontraction(C,A)
0

4) reverse works, when a coefficient is used:

julia> reverse(A)
-1e₂₃

julia> A
1e₂₃

**Comment by moble** [comment]
As for 3: It looks like `\cdot` [is imported from `LinearAlgebra`](https://github.com/digitaldomain/Multivectors.jl/blob/8898b44d604ffddd41ea2035a597138ec2344c4d/src/Blades.jl#L831), so if you do `using LinearAlgebra`, you'll have access to it simply as `\cdot[TAB]`.  I'd be cautious about it because it's defined on Blades again — though it does do some type promotion thing.  In any case, since there are different definitions of the "dot" product, check to see if it agrees with yours.  Also note that `symmetricdot` exists, and appears to also be exported as `\bullet[TAB]` — though that doesn't work for me either.  🤷
